variables:
  buildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: build
  
- script: dotnet pack Meziantou.GitLabClient/Meziantou.GitLabClient.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: pack
  
- script: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key $(NuGetApiKey) --force-english-output
  workingDirectory: $(Build.ArtifactStagingDirectory)
  displayName: push
  continueOnError: true
